#ifndef __CONFIG_HPP__
#define __CONFIG_HPP__

#define KERNEL_X 3
#define KERNEL_Y 3

#define CHANNELS_IN_CONV1 3
#define CHANNELS_OUT_CONV1 64
#define ROWS_CONV1 24
#define COLUMNS_CONV1 24

#define CHANNELS_IN_CONV2 64
#define CHANNELS_OUT_CONV2 32
#define ROWS_CONV2 12
#define COLUMNS_CONV2 12

#define CHANNELS_IN_CONV3 32
#define CHANNELS_OUT_CONV3 20
#define ROWS_CONV3 6
#define COLUMNS_CONV3 6

#define INPUT_SIZE_DENSE 180
#define OUTPUT_SIZE_DENSE 10

#define COEFFS_CONV1 (CHANNELS_OUT_CONV1*CHANNELS_IN_CONV1*KERNEL_X*KERNEL_Y)
#define COEFFS_CONV2 (CHANNELS_OUT_CONV2*CHANNELS_IN_CONV2*KERNEL_X*KERNEL_Y)
#define COEFFS_CONV3 (CHANNELS_OUT_CONV3*CHANNELS_IN_CONV3*KERNEL_X*KERNEL_Y)

#endif